const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Platform.Cnds.IsEnabled
	];
};
self.C3_JsPropNameTable = [
	{Платформер: 0},
	{СледитьЗа: 0},
	{Мигание: 0},
	{Твёрдый: 0},
	{Спрайт: 0},
	{Аудио: 0},
	{grassTile: 0},
	{ТайловыйФон: 0},
	{ТайловыйФон2: 0},
	{Клавиатура: 0},
	{Спрайт2: 0},
	{Поворот: 0},
	{Синусоида: 0},
	{Спрайт3: 0},
	{tilemap_black_packed: 0},
	{spike: 0},
	{spike2: 0},
	{СквознаяПлатформа: 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{Спрайт8: 0},
	{house: 0},
	{end: 0},
	{Угасание: 0},
	{fecclogo: 0},
	{Спрайт9: 0},
	{Текст: 0},
	{key: 0},
	{door: 0},
	{ТайловыйФон3: 0}
];

self.InstanceType = {
	Спрайт: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	grassTile: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	Клавиатура: class extends self.IInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	tilemap_black_packed: class extends self.ISpriteInstance {},
	spike: class extends self.ISpriteInstance {},
	spike2: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	house: class extends self.ISpriteInstance {},
	end: class extends self.ISpriteInstance {},
	fecclogo: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	key: class extends self.ISpriteInstance {},
	door: class extends self.ISpriteInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {}
}