const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.wrap,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Rotate.Acts.SetAcceleration,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SaveState,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{Твердый: 0},
	{Физика: 0},
	{КартаТайлов: 0},
	{скорПоден: 0},
	{Платформер: 0},
	{Замкнутость: 0},
	{Спрайт: 0},
	{ТайловыйФон: 0},
	{Клавиатура: 0},
	{Аудио: 0},
	{Текст: 0},
	{Поворот: 0},
	{Спрайт2: 0},
	{Частицы: 0},
	{Текст2: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Браузер: 0},
	{Спрайт5: 0},
	{Текст3: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{Текст4: 0},
	{Спрайт8: 0},
	{Спрайт9: 0},
	{Мышь: 0},
	{Спрайт10: 0},
	{Спрайт11: 0},
	{Текст5: 0}
];

self.InstanceType = {
	КартаТайлов: class extends self.ITilemapInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Клавиатура: class extends self.IInstance {},
	Аудио: class extends self.IInstance {},
	Текст: class extends self.ITextInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Частицы: class extends self.IParticlesInstance {},
	Текст2: class extends self.ITextInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Браузер: class extends self.IInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Текст4: class extends self.ITextInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Текст5: class extends self.ITextInstance {}
}