const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.wrap,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.sliderbar,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetLayoutEffectParam,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Rotate.Acts.SetAcceleration,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SaveState,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Browser.Acts.Close,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Text.Acts.TypewriterText
	];
};
self.C3_JsPropNameTable = [
	{Твердый: 0},
	{Физика: 0},
	{КартаТайлов: 0},
	{скорПоден: 0},
	{Платформер: 0},
	{Замкнутость: 0},
	{Твёрдый: 0},
	{Спрайт: 0},
	{ТайловыйФон: 0},
	{Клавиатура: 0},
	{Аудио: 0},
	{Текст: 0},
	{Поворот: 0},
	{Спрайт2: 0},
	{Частицы: 0},
	{Текст2: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Браузер: 0},
	{Спрайт5: 0},
	{Текст3: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{Текст4: 0},
	{Спрайт8: 0},
	{Спрайт9: 0},
	{Мышь: 0},
	{Спрайт10: 0},
	{Спрайт11: 0},
	{Текст5: 0},
	{Спрайт12: 0},
	{Пуля: 0},
	{Спрайт13: 0},
	{Спрайт14: 0},
	{Спрайт15: 0},
	{Спрайт16: 0},
	{Спрайт17: 0},
	{телевизр: 0},
	{телевизр2: 0},
	{Спрайт18: 0},
	{old_paper_on_the_table_: 0},
	{Спрайт19: 0},
	{Текст6: 0},
	{телевизр3: 0},
	{Спрайт20: 0},
	{телевизр4: 0},
	{Спрайт21: 0},
	{Ползунок: 0},
	{Твинанимация: 0},
	{Текст7: 0},
	{Спрайт22: 0},
	{Текст8: 0},
	{Текст9: 0},
	{Текст10: 0},
	{level: 0},
	{КартаТайлов2: 0},
	{ТайловыйФон2: 0},
	{Текст11: 0},
	{Спрайт23: 0},
	{Спрайт24: 0},
	{Частицы2: 0},
	{КартаТайлов3: 0},
	{КартаТайлов4: 0},
	{Угасание: 0},
	{level2: 0},
	{Спрайт25: 0},
	{Семья1: 0}
];

self.InstanceType = {
	КартаТайлов: class extends self.ITilemapInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Клавиатура: class extends self.IInstance {},
	Аудио: class extends self.IInstance {},
	Текст: class extends self.ITextInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Частицы: class extends self.IParticlesInstance {},
	Текст2: class extends self.ITextInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Браузер: class extends self.IInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Текст4: class extends self.ITextInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Текст5: class extends self.ITextInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	Спрайт14: class extends self.ISpriteInstance {},
	Спрайт15: class extends self.ISpriteInstance {},
	Спрайт16: class extends self.ISpriteInstance {},
	Спрайт17: class extends self.ISpriteInstance {},
	телевизр: class extends self.ISpriteInstance {},
	телевизр2: class extends self.ISpriteInstance {},
	Спрайт18: class extends self.ISpriteInstance {},
	old_paper_on_the_table_: class extends self.ISpriteInstance {},
	Спрайт19: class extends self.ISpriteInstance {},
	Текст6: class extends self.ITextInstance {},
	телевизр3: class extends self.ISpriteInstance {},
	Спрайт20: class extends self.ISpriteInstance {},
	телевизр4: class extends self.ISpriteInstance {},
	Спрайт21: class extends self.ISpriteInstance {},
	Ползунок: class extends self.ISliderBarInstance {},
	Текст7: class extends self.ITextInstance {},
	Спрайт22: class extends self.ISpriteInstance {},
	Текст8: class extends self.ITextInstance {},
	Текст9: class extends self.ITextInstance {},
	Текст10: class extends self.ITextInstance {},
	level: class extends self.ITextInstance {},
	КартаТайлов2: class extends self.ITilemapInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	Текст11: class extends self.ITextInstance {},
	Спрайт23: class extends self.ISpriteInstance {},
	Спрайт24: class extends self.ISpriteInstance {},
	Частицы2: class extends self.IParticlesInstance {},
	КартаТайлов3: class extends self.ITilemapInstance {},
	КартаТайлов4: class extends self.ITilemapInstance {},
	level2: class extends self.ITextInstance {},
	Спрайт25: class extends self.ISpriteInstance {},
	Семья1: class extends self.ISpriteInstance {}
}