const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.wrap,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.sliderbar,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Behaviors.Flash,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Plugins.gamepad,
		C3.Plugins.video,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetLayoutEffectParam,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Rotate.Acts.SetAcceleration,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SaveState,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetPreventRotate,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Acts.SetHAlign,
		C3.Plugins.Text.Acts.SetVAlign,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Tilemap.Acts.SetEffectParam,
		C3.Plugins.TiledBg.Acts.SetEffectParam,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.SetLayoutEffectEnabled,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.video.Cnds.IsVisible,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.video.Cnds.HasEnded
	];
};
self.C3_JsPropNameTable = [
	{Твердый: 0},
	{Физика: 0},
	{КартаТайлов: 0},
	{скорПоден: 0},
	{Платформер: 0},
	{Замкнутость: 0},
	{Твёрдый: 0},
	{Спрайт: 0},
	{ТайловыйФон: 0},
	{Клавиатура: 0},
	{Аудио: 0},
	{Текст: 0},
	{Поворот: 0},
	{Спрайт2: 0},
	{Частицы: 0},
	{Текст2: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Браузер: 0},
	{Спрайт5: 0},
	{Текст3: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{Текст4: 0},
	{Спрайт8: 0},
	{Спрайт9: 0},
	{Мышь: 0},
	{Спрайт10: 0},
	{Спрайт11: 0},
	{Текст5: 0},
	{Спрайт12: 0},
	{Пуля: 0},
	{Спрайт13: 0},
	{Спрайт14: 0},
	{Спрайт15: 0},
	{Спрайт16: 0},
	{Спрайт17: 0},
	{телевизр: 0},
	{телевизр2: 0},
	{Спрайт18: 0},
	{old_paper_on_the_table_: 0},
	{Спрайт19: 0},
	{Текст6: 0},
	{телевизр3: 0},
	{Спрайт20: 0},
	{телевизр4: 0},
	{Спрайт21: 0},
	{Ползунок: 0},
	{Твинанимация: 0},
	{Текст7: 0},
	{Спрайт22: 0},
	{Текст8: 0},
	{Текст9: 0},
	{Текст10: 0},
	{level: 0},
	{КартаТайлов2: 0},
	{ТайловыйФон2: 0},
	{Текст11: 0},
	{Спрайт23: 0},
	{Спрайт24: 0},
	{Частицы2: 0},
	{КартаТайлов3: 0},
	{КартаТайлов4: 0},
	{Угасание: 0},
	{level2: 0},
	{Спрайт25: 0},
	{Спрайт26: 0},
	{Спрайт27: 0},
	{menuBg: 0},
	{Синусоида: 0},
	{Синусоида2: 0},
	{Спрайт28: 0},
	{Мигание: 0},
	{mench: 0},
	{Текст13: 0},
	{load: 0},
	{exit: 0},
	{Спрайт29: 0},
	{val: 0},
	{savedelete: 0},
	{freeplay: 0},
	{A1: 0},
	{A2: 0},
	{A3: 0},
	{A4: 0},
	{A5: 0},
	{A6: 0},
	{A7: 0},
	{A8: 0},
	{A10: 0},
	{A11: 0},
	{A12: 0},
	{A9: 0},
	{NONE2: 0},
	{B1: 0},
	{B2: 0},
	{B3: 0},
	{B4: 0},
	{B5: 0},
	{B6: 0},
	{B7: 0},
	{B8: 0},
	{NONE3: 0},
	{Текст12: 0},
	{Текст14: 0},
	{Noise: 0},
	{Sound: 0},
	{noisem: 0},
	{Autosave: 0},
	{Спрайт30: 0},
	{Спрайт31: 0},
	{Спрайт32: 0},
	{ТайловыйФон3: 0},
	{SoundTest: 0},
	{ChooseMenu: 0},
	{UpdateLog: 0},
	{Noise2: 0},
	{Словарь: 0},
	{ЛокальноеХранилище: 0},
	{new: 0},
	{old: 0},
	{Геймпад: 0},
	{Спрайт33: 0},
	{Спрайт34: 0},
	{Спрайт35: 0},
	{older: 0},
	{noise_factor: 0},
	{HINT: 0},
	{noisenind: 0},
	{Текст15: 0},
	{noisemaker: 0},
	{Спрайт36: 0},
	{grass: 0},
	{groundfake: 0},
	{tilefake: 0},
	{death: 0},
	{ground: 0},
	{BGchunk: 0},
	{ТайловыйФон4: 0},
	{Видео: 0},
	{LOADING: 0},
	{B9: 0},
	{B10: 0},
	{B11: 0},
	{B12: 0},
	{Семья1: 0},
	{sel: 0},
	{row: 0},
	{enabled: 0},
	{was: 0},
	{rowsel: 0},
	{rowsel2: 0},
	{rowsel3: 0},
	{s_c_1: 0},
	{noise_lv: 0},
	{s_c_2: 0},
	{s_men_s: 0},
	{noise_en: 0},
	{en: 0},
	{rowsel4: 0}
];

self.InstanceType = {
	КартаТайлов: class extends self.ITilemapInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Клавиатура: class extends self.IInstance {},
	Аудио: class extends self.IInstance {},
	Текст: class extends self.ITextInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Частицы: class extends self.IParticlesInstance {},
	Текст2: class extends self.ITextInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Браузер: class extends self.IInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Текст4: class extends self.ITextInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Текст5: class extends self.ITextInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	Спрайт14: class extends self.ISpriteInstance {},
	Спрайт15: class extends self.ISpriteInstance {},
	Спрайт16: class extends self.ISpriteInstance {},
	Спрайт17: class extends self.ISpriteInstance {},
	телевизр: class extends self.ISpriteInstance {},
	телевизр2: class extends self.ISpriteInstance {},
	Спрайт18: class extends self.ISpriteInstance {},
	old_paper_on_the_table_: class extends self.ISpriteInstance {},
	Спрайт19: class extends self.ISpriteInstance {},
	Текст6: class extends self.ITextInstance {},
	телевизр3: class extends self.ISpriteInstance {},
	Спрайт20: class extends self.ISpriteInstance {},
	телевизр4: class extends self.ISpriteInstance {},
	Спрайт21: class extends self.ISpriteInstance {},
	Ползунок: class extends self.ISliderBarInstance {},
	Текст7: class extends self.ITextInstance {},
	Спрайт22: class extends self.ISpriteInstance {},
	Текст8: class extends self.ITextInstance {},
	Текст9: class extends self.ITextInstance {},
	Текст10: class extends self.ITextInstance {},
	level: class extends self.ITextInstance {},
	КартаТайлов2: class extends self.ITilemapInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	Текст11: class extends self.ITextInstance {},
	Спрайт23: class extends self.ISpriteInstance {},
	Спрайт24: class extends self.ISpriteInstance {},
	Частицы2: class extends self.IParticlesInstance {},
	КартаТайлов3: class extends self.ITilemapInstance {},
	КартаТайлов4: class extends self.ITilemapInstance {},
	level2: class extends self.ITextInstance {},
	Спрайт25: class extends self.ISpriteInstance {},
	Спрайт26: class extends self.ISpriteInstance {},
	Спрайт27: class extends self.ISpriteInstance {},
	menuBg: class extends self.ISpriteInstance {},
	Спрайт28: class extends self.ISpriteInstance {},
	mench: class extends self.ITextInstance {},
	Текст13: class extends self.ITextInstance {},
	load: class extends self.ITextInstance {},
	exit: class extends self.ITextInstance {},
	Спрайт29: class extends self.ISpriteInstance {},
	val: class extends self.ITextInstance {},
	savedelete: class extends self.ITextInstance {},
	freeplay: class extends self.ITextInstance {},
	A1: class extends self.ITextInstance {},
	A2: class extends self.ITextInstance {},
	A3: class extends self.ITextInstance {},
	A4: class extends self.ITextInstance {},
	A5: class extends self.ITextInstance {},
	A6: class extends self.ITextInstance {},
	A7: class extends self.ITextInstance {},
	A8: class extends self.ITextInstance {},
	A10: class extends self.ITextInstance {},
	A11: class extends self.ITextInstance {},
	A12: class extends self.ITextInstance {},
	A9: class extends self.ITextInstance {},
	NONE2: class extends self.ITextInstance {},
	B1: class extends self.ITextInstance {},
	B2: class extends self.ITextInstance {},
	B3: class extends self.ITextInstance {},
	B4: class extends self.ITextInstance {},
	B5: class extends self.ITextInstance {},
	B6: class extends self.ITextInstance {},
	B7: class extends self.ITextInstance {},
	B8: class extends self.ITextInstance {},
	NONE3: class extends self.ITextInstance {},
	Текст12: class extends self.ITextInstance {},
	Текст14: class extends self.ITextInstance {},
	Noise: class extends self.ITextInstance {},
	Sound: class extends self.ITextInstance {},
	noisem: class extends self.ITextInstance {},
	Autosave: class extends self.ITextInstance {},
	Спрайт30: class extends self.ISpriteInstance {},
	Спрайт31: class extends self.ISpriteInstance {},
	Спрайт32: class extends self.ISpriteInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	SoundTest: class extends self.ITextInstance {},
	ChooseMenu: class extends self.ITextInstance {},
	UpdateLog: class extends self.ITextInstance {},
	Noise2: class extends self.ITextInstance {},
	Словарь: class extends self.IDictionaryInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	new: class extends self.ITextInstance {},
	old: class extends self.ITextInstance {},
	Геймпад: class extends self.IInstance {},
	Спрайт33: class extends self.ISpriteInstance {},
	Спрайт34: class extends self.ISpriteInstance {},
	Спрайт35: class extends self.ISpriteInstance {},
	older: class extends self.ITextInstance {},
	noise_factor: class extends self.ITextInstance {},
	HINT: class extends self.ITextInstance {},
	noisenind: class extends self.ITextInstance {},
	Текст15: class extends self.ITextInstance {},
	noisemaker: class extends self.ISpriteInstance {},
	Спрайт36: class extends self.ISpriteInstance {},
	grass: class extends self.ITilemapInstance {},
	groundfake: class extends self.ITilemapInstance {},
	tilefake: class extends self.ITiledBackgroundInstance {},
	death: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	BGchunk: class extends self.ISpriteInstance {},
	ТайловыйФон4: class extends self.ITiledBackgroundInstance {},
	Видео: class extends self.IWorldInstance {},
	LOADING: class extends self.ITextInstance {},
	B9: class extends self.ITextInstance {},
	B10: class extends self.ITextInstance {},
	B11: class extends self.ITextInstance {},
	B12: class extends self.ITextInstance {},
	Семья1: class extends self.ISpriteInstance {}
}